#!/bin/bash
ownerName=$1
appName=$2
appCenterToken=$3

apiUrl="https://api.appcenter.ms/v0.1/apps/$ownerName/$appName/release_uploads"
curl -X POST $apiUrl -H "accept: application/json" -H "Content-Type: application/json" -H "X-API-Token: $appCenterToken"
