#!/bin/bash
export PATH=$PATH:./scripts
ownerName=$1
appName=$2
appCenterToken=$3
apkPath=$4
notes="release"
#groupId=$5

jsonString=`uploadAndroidScript $1 $2 $3`
uploadId=`echo $jsonString| jq ".upload_id" | xargs`
uploadUrl=`echo $jsonString| jq ".upload_url" | xargs`

if [ -z "$uploadId" ]
then
      exit -1
else
      exit 0
fi

if [ -z "$uploadUrl" ]
then
      exit -1
else
      exit 0
fi

uploadBuild $uploadUrl $apkPath $notes $appCenterToken
jsonString=`commitUploadResource $uploadId $ownerName $appName $appCenterToken`
releaseId=`echo $jsonString| jq ".release_id" | xargs`
if [ -z "$releaseId" ]
then
      exit -1
else
      exit 0
fi
#updateToGroupId ownerName appName appCenterToken releaseId groupId